# Site settings
title: Claudio Zeeb
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Claudio Zeeb
user_description: I'm a lighting programmer from Munich, Germany. Since starting out as an operator at the Münchner Kammerspiele in 2017, I have programmed and designed shows for a number of theatre and opera houses across Europe.
user_title: Lighting Programmer
email: claudio.zeeb@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
